### ISSUE TITLE
Project does not compile in Eclipse

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-deployer-cloudfoundry#13]
It could be a JDT bug, but it would be nice to either get that fixed or refactor to make the compiler happy.

**Comment by aclement** [comment]
I'll give it a go and raise an Eclipse bug if necessary.

**Comment by aclement** [comment]
Just to note - yesterday it wasn't compiling for me - looked like a mismatch in a snapshot dependency (a method had perhaps been changed in the v2 CF java client in a more recent snapshot to have 2 parameters rather than 1) - but i didn't have time to investigate further. I also had issues because the m2e groovy configurator wasn't installed. Today, with the configurator installed, it is now building fine for me. Although not totally sure if that is because my maven cache accidentally has the right snapshot of the client lib in now.

**Comment by gregturn** [comment]
This may be resolved via #55
