### ISSUE TITLE
Can not disable autoconfiguration

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-deployer-cloudfoundry#208]
There is an inner class in the autoconfiguration and according to

https://github.com/spring-projects/spring-boot/issues/5427

boot does not allow disabling of inner classes for autoconfiguration.

EarlyConnectionConfiguration should be moved its own class.

**Comment by markpollack** [comment]
Actually, it excluding it seems to work, but only if I add the exclude on the main application

```
@SpringBootApplication
@EnableAutoConfiguration(exclude = CloudFoundryDeployerAutoConfiguration.class)
public class SkipperServerApplication {
```

when I apply it to 
```
@Configuration
@EnableConfigurationProperties({ SkipperServerProperties.class, CloudFoundryPlatformAccounts.class })
@EnableAutoConfiguration(exclude = CloudFoundryDeployerAutoConfiguration.class)
public class SkipperServerConfiguration {
}```

it doesn't work.

**Comment by ilayaperumalg** [comment]
@markpollack This is because the main application already has `EnableAutoConfiguration` via `SpringBootApplication` which triggers the actual `EnableAutoConfiguration` for the Skipper server application. Hence, the `exclude` needs to be provided in the main application (where the `EnableAutoConfiguration` is already present via `@SpringBootApplication` )
